name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 프로젝트 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Node.js 환경 설정
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # 3. coins-react 빌드
    - name: Install dependencies for coins-react
      working-directory: ./coins-server/coins-react
      run: npm install

    - name: Build coins-react
      working-directory: ./coins-server/coins-react
      run: npm run build

    # 4. coins-server 작업
    - name: Install dependencies for coins-server
      working-directory: ./coins-server
      run: npm install

    - name: Run tests for coins-server
      working-directory: ./coins-server
      run: npm test -- --detectOpenHandles

    # 5. 배포 단계
    - name: Deploy to server
      run: echo "Deploying application..."
