name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 프로젝트 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Node.js 환경 설정
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # 3. npm 캐시를 설정하여 종속성 설치 최적화
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    # 4. coins-react 빌드
    - name: Install dependencies for coins-react
      working-directory: ./coins-server/coins-react
      run: npm install

    - name: Build coins-react
      working-directory: ./coins-server/coins-react
      run: npm run build

    # 5. coins-server 작업
    - name: Install dependencies for coins-server
      working-directory: ./coins-server
      run: npm ci

    # 6. 테스트 실행
    - name: Run tests for coins-server
      working-directory: ./coins-server
      run: npm test -- --detectOpenHandles

    # 배포 단계를 제외하고 빌드만 확인
